### PR TITLE
Update jqeury

### PR DESCRIPTION
**Pull request by kiloreux**
This updates the jQuery to v3.

Closing this fixes https://github.com/transloadit/rails-sdk/issues/59

### CODE REVIEW

**Comment by rmehner** [comment]
Thanks 🙏 

This is a potential BC breaking change and we should add that to the changelog.

**Comment by kvz** [comment]
How about major bumping the rails-sdk along with it?

**Comment by kvz** [comment]
Crazy unrelated thought, as we're gradually phasing out the jquery-sdk, should the rails-sdk start adopting https://uppy.io at some point? Any hard reason for not wanting that?

**Comment by rmehner** [comment]
> How about major bumping the rails-sdk along with it?

Yes, we need to do that for other things as well, but I'm a bit out of time unfortunately :/

> [..] unrelated thought, as we're gradually phasing out the jquery-sdk, should the rails-sdk start adopting https://uppy.io at some point? Any hard reason for not wanting that?

Nope. I don't have any experiences with uppy yet (although we'll probably add it in some project very soon), but the part that we're using jQuery for, could probably also work with uppy, if not better. Is browser support on par with what the jquery-sdk has?

**Comment by kvz** [comment]
Awesome to hear! Yeah not saying anything about timeframes, and maybe someone from our team can get more weight behind it, but if we all agree about what should be roadmap that already helps a lot.

I guess it is related in the way that, if we want a new major, maybe we can bundle a whole bunch of breaking stuff in that release.

> Is browser support on par with what the jquery-sdk has?

It's not, so that's another breaking thing then. Uppy [targets IE10+](https://uppy.io/docs/#Browser-Support), the jquery-sdk has a farther reach into the past I believe. But I also believe v3 already leaves a few browsers behind compared to v2, maybe @tim-kos can fill us in here.

**Comment by tim-kos** [comment]
jQuery SDK v3 introduced websocket for Assembly-related events, so she is also IE10+. :)

> How about major bumping the rails-sdk along with it?

+1

> Unrelated thought, as we're gradually phasing out the jquery-sdk, should the rails-sdk start adopting https://uppy.io at some point? Any hard reason for not wanting that?

+1

**Comment by kvz** [comment]
Let's save Uppy for a different time.

@kiloreux can you bump the version in the CHANGELOG so this rails-sdk can then be released with a new major as well?

**Comment by kiloreux** [comment]
Done here https://github.com/transloadit/rails-sdk/pull/62

**Comment by kvz** [comment]
👍

**Pull request closed without merging**
