### PR TITLE
docs: refine readme + small rails example app

### PR DESCRIPTION
**Pull request by ifedapoolarewaju**

### CODE REVIEW

**Comment by rmehner** [comment]
I general I am in favor of this, but what do you think of making the example app a different repo that we point people to?

If we want to keep it in this repository, we should at least exclude it from the produced gem, so it doesn't blow up the size and makes installing smaller (right now, we include all files to the gem, see https://github.com/transloadit/rails-sdk/blob/c6124e5f1491bbb5c8dbf955addbeeaf0303126a/transloadit-rails.gemspec#L22)

**Comment by ifedapoolarewaju** [comment]
ooh yes I totally agree with you on that. would [this](https://github.com/ifedapoolarewaju/rails-sdk/blob/refine-readme/transloadit-rails.gemspec#L23) make sense as an appropriate solution?

I think generally, having less repos to maintain is favored so maybe leaving it in this repo but excluding it from the gem files as you suggested would make sense?

**Comment by kvz** [comment]
> I general I am in favor of this, but what do you think of making the example app a different repo that we point people to?

I hear what you're saying Robin, we're a bit torn on this currently. In the light of we'd have 10 sdk repos + 10 sdk example repos, we currently side on bundling (>=)one example per repository. This also makes it easer to pair bc-breaking changes. If we grow overly tired or irritated, we'll definitely revisit and maybe still split them up.

> excluding it from the gem

Great idea 💯

**Comment by rmehner** [comment]
> I hear what you're saying Robin, we're a bit torn on this currently. In light of having 10 sdk repos + 10 sdk example repos, we currently side on bundling (>=)one example per repository.

Yes, on the other hand if the example app is in a different repo, people can just clone that repo and start customizing for their own app. Guess both has advantages. Your call :) I don't feel strongly about this.

> This also makes it easier to pair bc-breaking changes, and increase the likelyhood of examples actually still working.

🤔  it would be great if we would have a full blown example app that uses latest master to run their acceptance test suite. But that's a different story.



> ooh yes I totally agree with you on that. would this make sense as an appropriate solution?

@ifedapoolarewaju yep, that works. Sometimes Ruby is beautiful :)

**Comment by ifedapoolarewaju** [comment]
@kvz are we good to merge this? I have excluded the `examples` directory from the gem as Robin suggested.

**Comment by kvz** [comment]
Yes, looking good, thanks for the reminder Ife!

**Pull request merged**
