### PR TITLE
Upgrade jQuery

### PR DESCRIPTION
**Pull request by kiloreux**
Same as https://github.com/transloadit/rails-sdk/pull/60

Just deleted the orginial fork repo.

### CODE REVIEW

**Review by kvz — APPROVED** [review]
Thanks mister!

**Comment by kvz** [comment]
Now all we need is someone who knows how to cut a gem release from master, @juliangruber is this something you've done before?

**Comment by juliangruber** [comment]
I haven't but I'm sure I can figure this out. Do you want this nowish or is next week ok?

**Comment by kvz** [comment]
No, this has been pending for very long so next week is certainly fine. I thought you were the one with some Ruby experience. Perhaps I 'membered wrong  🤔 will ask in the team cause then it may make more sense for someone else to take this over. Ruby is the thing we don't really have covered yet with Ife away.

**Comment by juliangruber** [comment]
I have ruby experience yeah, and I think I have published a gem before, but long ago. I have more consumer experience.

**Pull request merged**
